import React, { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import './DriftWall.css';

const prefersReducedMotion = () => typeof window !== 'undefined' && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const columnFactor = (index, variance) => 1 + variance * ((((index * 0.6180339887 + 0.35) % 1) * 2) - 1);

export default function DriftWall({ items = [], columns = 5, tileWidth = 200, tileHeight = 132, gap = 18, radius = 14, tilt = 16, turn = -14, roll = 0, perspective = 1200, depth = 120, speed = 42, direction = 'up', variance = 0.45, parallax = 0.6, pauseOnHover = false, lift = 64, fade = 0.6, dim = 0.55, grayscale = false, overlayColor = '#060010', onSelect, favorites = [], onFavorite }) {
  const containerRef = useRef(null), planeRef = useRef(null), trackRefs = useRef([]), rafRef = useRef(null);
  const offsetsRef = useRef([]), velocitiesRef = useRef([]), hoveredColRef = useRef(-1), wallHoveredRef = useRef(false), pointerRef = useRef({ x: 0, y: 0 }), pointerDampedRef = useRef({ x: 0, y: 0 }), lastTsRef = useRef(null), activeIdRef = useRef(null);
  const [containerHeight, setContainerHeight] = useState(600), [activeId, setActiveId] = useState(null), [reduced, setReduced] = useState(false);
  const columnItems = useMemo(() => { const cols = Array.from({ length: columns }, () => []); items.forEach((item, index) => cols[index % columns].push(item)); return cols.map((col) => col.length ? col : items.slice(0, 1)); }, [items, columns]);
  const columnMeta = useMemo(() => columnItems.map((col) => { const unit = tileHeight + gap; const copyHeight = Math.max(unit, col.length * unit); return { copyHeight, copies: Math.max(2, Math.ceil((containerHeight * 1.6) / copyHeight) + 1) }; }), [columnItems, tileHeight, gap, containerHeight]);
  const baseVelocities = useMemo(() => { const dirSign = direction === 'up' ? 1 : -1; return columnItems.map((_, index) => speed * columnFactor(index, variance) * dirSign * (index % 2 === 0 ? 1 : -1)); }, [columnItems, speed, direction, variance]);

  useEffect(() => { setReduced(prefersReducedMotion()); const mq = window.matchMedia('(prefers-reduced-motion: reduce)'); const onChange = (event) => setReduced(event.matches); mq.addEventListener('change', onChange); return () => mq.removeEventListener('change', onChange); }, []);
  useLayoutEffect(() => { if (!containerRef.current) return undefined; const ro = new ResizeObserver(([entry]) => setContainerHeight(entry.contentRect.height || 600)); ro.observe(containerRef.current); return () => ro.disconnect(); }, []);
  useEffect(() => { offsetsRef.current = columnMeta.map((meta, index) => meta.copyHeight * ((index * 0.37) % 1)); velocitiesRef.current = columnItems.map(() => 0); }, [columnMeta, columnItems]);
  const applyPlaneTransform = useCallback((px, py) => { if (planeRef.current) planeRef.current.style.transform = `translate(-50%, -50%) scale(1.18) rotateX(${tilt + py}deg) rotateY(${turn + px}deg) rotateZ(${roll}deg) translateZ(${-depth}px)`; }, [tilt, turn, roll, depth]);
  useEffect(() => { const animate = (ts) => { if (lastTsRef.current === null) lastTsRef.current = ts; const dt = Math.min(0.05, Math.max(0, ts - lastTsRef.current) / 1000); lastTsRef.current = ts; const maxTilt = parallax * 8, damp = 1 - Math.exp(-dt / 0.12); pointerDampedRef.current.x += (pointerRef.current.x * maxTilt - pointerDampedRef.current.x) * damp; pointerDampedRef.current.y += (-pointerRef.current.y * maxTilt - pointerDampedRef.current.y) * damp; applyPlaneTransform(pointerDampedRef.current.x, pointerDampedRef.current.y); columnMeta.forEach((meta, index) => { const track = trackRefs.current[index]; if (!track) return; const target = reduced || (wallHoveredRef.current && pauseOnHover) || hoveredColRef.current === index ? 0 : baseVelocities[index]; const ease = 1 - Math.exp(-dt / (target === 0 ? 0.16 : 0.28)); velocitiesRef.current[index] += (target - velocitiesRef.current[index]) * ease; offsetsRef.current[index] = ((offsetsRef.current[index] + velocitiesRef.current[index] * dt) % meta.copyHeight + meta.copyHeight) % meta.copyHeight; track.style.transform = `translate3d(0, ${-offsetsRef.current[index]}px, 0)`; }); rafRef.current = requestAnimationFrame(animate); }; rafRef.current = requestAnimationFrame(animate); return () => { cancelAnimationFrame(rafRef.current); lastTsRef.current = null; }; }, [applyPlaneTransform, baseVelocities, columnMeta, pauseOnHover, parallax, reduced]);
  const activate = useCallback((id, index) => { activeIdRef.current = id; hoveredColRef.current = index; setActiveId(id); }, []);
  const release = useCallback(() => { activeIdRef.current = null; hoveredColRef.current = -1; setActiveId(null); }, []);
  const handlePointerMove = useCallback((event) => { const rect = containerRef.current?.getBoundingClientRect(); if (!rect) return; if (parallax > 0 && !reduced) pointerRef.current = { x: (event.clientX - rect.left) / rect.width - 0.5, y: (event.clientY - rect.top) / rect.height - 0.5 }; const tile = document.elementFromPoint(event.clientX, event.clientY)?.closest?.('[data-tile-id]'); if (tile && tile.dataset.tileId !== activeIdRef.current) activate(tile.dataset.tileId, Number(tile.dataset.col)); }, [activate, parallax, reduced]);
  const cssVars = { '--dw-tile-w': `${tileWidth}px`, '--dw-tile-h': `${tileHeight}px`, '--dw-gap': `${gap}px`, '--dw-radius': `${radius}px`, '--dw-perspective': `${perspective}px`, '--dw-lift': `${lift}px`, '--dw-dim': dim, '--dw-gray': grayscale ? 1 : 0, '--dw-overlay': overlayColor, '--dw-edge': `${Math.max(0, (1 - fade) * 100)}%` };
  const renderTile = (item, id, colIndex) => <div key={id} className={`drift-wall__tile${activeId === id ? ' is-active' : ''}`} data-tile-id={id} data-col={colIndex} tabIndex={0} role="button" aria-label={item.title || 'tile'} onClick={() => onSelect?.(item)} onFocus={() => activate(id, colIndex)} onBlur={release}><span className="drift-wall__inner"><img src={item.image} alt={item.title || ''} loading="lazy" decoding="async" draggable="false" /><span className="drift-wall__overlay" /></span><span className="drift-wall__label">{item.title}</span>{onFavorite && <button className={`drift-wall__favorite${favorites.includes(item.title) ? ' is-favorite' : ''}`} onClick={(event) => { event.stopPropagation(); onFavorite(item.title); }} aria-label={`Save ${item.title}`}>{favorites.includes(item.title) ? '♥' : '♡'}</button>}</div>;
  return <div ref={containerRef} className={`drift-wall${reduced ? ' drift-wall--reduced' : ''}`} style={cssVars} onPointerMove={handlePointerMove} onPointerEnter={() => { wallHoveredRef.current = true; }} onPointerLeave={() => { wallHoveredRef.current = false; pointerRef.current = { x: 0, y: 0 }; release(); }} role="group" aria-label="Drifting wall of tiles"><div ref={planeRef} className="drift-wall__plane">{columnItems.map((col, index) => <div className="drift-wall__col" key={`col-${index}`}><div className="drift-wall__track" ref={(element) => { trackRefs.current[index] = element; }}>{Array.from({ length: columnMeta[index].copies }).flatMap((_, copy) => col.map((item, itemIndex) => renderTile(item, `${index}-${copy}-${itemIndex}`, index)))}</div></div>)}</div></div>;
}
